# Generated by Django 3.0.5 on 2020-11-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='invoice_no',
            field=models.CharField(default='01b1aec6', max_length=8),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='invoice_no',
            field=models.CharField(default='84690098', max_length=8),
        ),
    ]
