# Generated by Django 3.0.5 on 2020-11-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='invoice_no',
            field=models.CharField(default='7f3cece0', max_length=8),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='invoice_no',
            field=models.CharField(default='58b8cc9c', max_length=8),
        ),
    ]
