# Generated by Django 3.0.5 on 2020-11-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20201121_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='invoice_no',
            field=models.CharField(default='2ac2349b', max_length=8),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='invoice_no',
            field=models.CharField(default='ce406376', max_length=8),
        ),
    ]
