# Generated by Django 3.0.5 on 2020-11-22 15:06

import apps.core.base.utils.basic
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20201122_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='invoice_no',
            field=models.CharField(default=apps.core.base.utils.basic.random_hex_code, max_length=8),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='invoice_no',
            field=models.CharField(default=apps.core.base.utils.basic.random_hex_code, max_length=8),
        ),
    ]
