# Generated by Django 3.0.5 on 2020-11-26 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20201122_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Mobile number must be a valid bangladeshi number', regex='\\+?(88)?01[3456789][0-9]{8}$')]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='mobile',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Mobile number must be a valid bangladeshi number', regex='\\+?(88)?01[3456789][0-9]{8}$')]),
        ),
    ]
