# Generated by Django 3.0.5 on 2020-11-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20201126_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
