# Generated by Django 3.0.5 on 2020-11-27 10:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20201127_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='organization_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='organization_name',
        ),
        migrations.AddField(
            model_name='product',
            name='lowest_selling_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_id', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Vendor contains alphanumeric, underscore, space and period(.). Length: 2 to 100', regex='[-a-zA-Z0-9_.\\s]{2,100}$')])),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_type_category', to='inventory.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_unit', to='inventory.UnitType'),
            preserve_default=False,
        ),
    ]
