# Generated by Django 3.0.5 on 2020-11-29 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20201128_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Mobile number must be a valid Bangladeshi number', regex='\\+?(88)?01[3456789][0-9]{8}$')]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='mobile',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Mobile number must be a valid Bangladeshi number', regex='\\+?(88)?01[3456789][0-9]{8}$')]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Vendor contains alphanumeric, underscore, space and period(.). Length: 2 to 100', regex='[-a-zA-Z0-9_.\\s]{2,100}$')]),
        ),
    ]
