# Generated by Django 3.0.5 on 2020-12-01 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20201129_1200'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('name', 'category')},
        ),
    ]
