# Generated by Django 3.0.5 on 2020-04-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20200427_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='created_date',
        ),
    ]
