# Generated by Django 3.0.5 on 2020-04-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_remove_role_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='updated_date',
        ),
    ]
