# Generated by Django 3.0.5 on 2020-05-08 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_remove_role_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='created_by',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='updated_by',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='updated_by',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='created_by',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='updated_by',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='created_by',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='updated_by',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domain',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_customer', to='rbac.Customer'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='feature_customers', to='rbac.Customer'),
        ),
    ]
