# Generated by Django 3.0.5 on 2020-05-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20200508_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='created_by',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='feature',
            name='updated_by',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_by',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='group',
            name='updated_by',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='permission',
            name='created_by',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='permission',
            name='updated_by',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_by',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_by',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
