# Generated by Django 3.0.5 on 2020-05-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_auto_20200522_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='browser_details',
            field=models.CharField(default='1', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
