# Generated by Django 3.0.5 on 2020-07-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0013_feature_order_for_sidebar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(default='', max_length=50),
        ),
    ]
