# Generated by Django 3.0.5 on 2020-11-18 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0016_branch_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department_branch', to='rbac.Branch'),
            preserve_default=False,
        ),
    ]
