# Generated by Django 3.0.5 on 2020-11-18 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0017_department_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branch_customer', to='rbac.Customer'),
            preserve_default=False,
        ),
    ]
