# Generated by Django 3.0.5 on 2020-11-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0018_auto_20201118_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='hashed_id',
            field=models.CharField(default='6g45', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='hashed_id',
            field=models.CharField(default='sdfwef43', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='hashed_id',
            field=models.CharField(default='sdf4', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='hashed_id',
            field=models.CharField(default='sdv436', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='hashed_id',
            field=models.CharField(default='8i65h', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='hashed_id',
            field=models.CharField(default='sdf3th', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='hashed_id',
            field=models.CharField(default='dsf33', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpassword',
            name='hashed_id',
            field=models.CharField(default='btg54', max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
