# Generated by Django 3.0.5 on 2020-11-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0020_auto_20201126_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='hashed_id',
            field=models.CharField(default=1, max_length=8),
        ),
        migrations.AlterField(
            model_name='branch',
            name='hashed_id',
            field=models.CharField(default=1, max_length=8),
        ),
        migrations.AlterField(
            model_name='department',
            name='hashed_id',
            field=models.CharField(default=1, max_length=8),
        ),
        migrations.AlterField(
            model_name='feature',
            name='hashed_id',
            field=models.CharField(default=1, max_length=8),
        ),
        migrations.AlterField(
            model_name='group',
            name='hashed_id',
            field=models.CharField(default=1, max_length=8),
        ),
        migrations.AlterField(
            model_name='permission',
            name='hashed_id',
            field=models.CharField(default=1, max_length=8),
        ),
        migrations.AlterField(
            model_name='role',
            name='hashed_id',
            field=models.CharField(default=1, max_length=8),
        ),
        migrations.AlterField(
            model_name='userpassword',
            name='hashed_id',
            field=models.CharField(default=1, max_length=8),
        ),
    ]
