# Generated by Django 3.0.5 on 2020-11-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0022_auto_20201126_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userpassword',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
