# Generated by Django 3.0.5 on 2020-11-29 06:00

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0023_auto_20201127_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=50, unique=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='client/')),
                ('address', models.CharField(max_length=500)),
                ('status', models.IntegerField(choices=[(1, 'General User'), (2, 'Pro User')])),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='branch',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='customers',
        ),
        migrations.AddField(
            model_name='branch',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branch_client', to='rbac.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='feature_client', to='rbac.Client'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='rbac.Client'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
