# Generated by Django 3.0.5 on 2020-11-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0024_auto_20201129_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together={('title', 'parent')},
        ),
    ]
