# Generated by Django 3.0.5 on 2020-12-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0025_auto_20201129_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpassword',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
