# Generated by Django 3.0.5 on 2020-12-06 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0026_auto_20201202_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subbranches', to='rbac.Branch'),
        ),
    ]
