# Generated by Django 3.0.5 on 2020-12-08 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0027_auto_20201206_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Branch contains alphanumeric, underscore, space and period(.). Length: 2 to 100', regex='[-a-zA-Z0-9_.\\s]{2,100}$')]),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('name', 'parent')},
        ),
    ]
