# Generated by Django 3.0.5 on 2021-01-03 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0028_auto_20201208_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ('name',)},
        ),
    ]
