# Generated by Django 3.0.5 on 2021-01-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0031_branch_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='path',
            field=models.TextField(default=''),
        ),
    ]
